name: CI

on:
  pull_request:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JVM
        uses: actions/setup-java@v4
        with:
          java-version: "24"
          distribution: "zulu"
          cache: "sbt"
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Cache SBT
        uses: actions/cache@v4
        with:
            path: |
              ~/.ivy2/cache
              ~/.ivy2/local
              **/target/**
              ~/.sbt
            key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/*.sbt', 'project/*.scala') }}
            restore-keys: |
              ${{ runner.os }}-sbt-
      - name: Test
        run: sbt "magnumZio/test"
